pipeline {
    agent any

    environment {
        IMAGE_NAME = "springboot-devops-app:v1"
        CLUSTER_NAME = "dev-cluster"
        KUBECONFIG = "/root/.kube/config"
    }

    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/jsonam21/Devops_Demo_Project.git'
            }
        }

        stage('Build JAR') {
            steps {
                sh 'cd application/springboot-app && mvn clean package'
            }
        }

        stage('Build docker image') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME \
                -f application/dockerfile \
                application
                '''
            }
        }

        stage('Load image to KIND') {
            steps {
                sh 'kind load docker-image $IMAGE_NAME --name $CLUSTER_NAME'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'cd ..'
                sh 'kubectl apply -f kubernetes/'
            }
        }

        
    }
}