pipeline {
    agent any

    environment {
        IMAGE_NAME = "springboot-devops-app:v1"
        CLUSTER_NAME = "dev-cluster"
        KUBECONFIG = "/opt/kube/config"
        BUILD_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/jsonam21/Devops_Demo_Project.git'
            }
        }

        stage('Build JAR') {
            steps {
                sh 'cd application/springboot-app && mvn clean package'
            }
        }

        stage('Build docker image') {
            steps {
                sh '''
                docker build -t ${IMAGE_NAME}:${BUILD_TAG} \
                -f application/dockerfile \
                application
                '''
            }
        }

        stage('Load image to KIND') {
            steps {
                sh 'kind load docker-image ${IMAGE_NAME}:${BUILD_TAG} --name $CLUSTER_NAME'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'cd ..'
                sh 'kubectl apply -f kubernetes/'
            }
        }

        stage('Update Kubernetes Deployment') {
            steps {
                sh '''
                kubectl set image deployment/springboot-app \
                springboot-app=${IMAGE_NAME}:{BUILD_TAG} \
                -n devops-demo
                '''
            }
        }

         stage('Validate Deployment') {
            steps {
                sh '''
                kubectl rollout status \
                deployment/springboot-app \
                -n devops-demo
                '''
            }
         }
        
    }

    post {
        success {
            echo 'Deployment successful!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}